version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
# docker run -p 9000:9000 -p 9001:9001 --name minio1 \
#   -v minio_data:/data \
#   -e "MINIO_ROOT_USER=<YOUR_ACCESS_KEY>" \
#   -e "MINIO_ROOT_PASSWORD=<YOUR_SECRET_KEY>" \
#   minio/minio server /data --console-address ":9001"

#http://localhost:9001/buckets

#https://github.com/minio/mc
